//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesoIdeal {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PesoIdeal.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than normal.
        /// </summary>
        public static string A_MenorNormal {
            get {
                return ResourceManager.GetString("A_MenorNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About_Text {
            get {
                return ResourceManager.GetString("About_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Aceptar_Text {
            get {
                return ResourceManager.GetString("Aceptar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add_Text {
            get {
                return ResourceManager.GetString("Add_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tall.
        /// </summary>
        public static string Altura_Text {
            get {
                return ResourceManager.GetString("Altura_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal weight.
        /// </summary>
        public static string B_Normal {
            get {
                return ResourceManager.GetString("B_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back_Text {
            get {
                return ResourceManager.GetString("Back_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overweight.
        /// </summary>
        public static string C_Sobrepeso {
            get {
                return ResourceManager.GetString("C_Sobrepeso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancelar_Text {
            get {
                return ResourceManager.GetString("Cancelar_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out my others apps and games.
        /// </summary>
        public static string CheckApplications_Text {
            get {
                return ResourceManager.GetString("CheckApplications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, complete all information requested, thanks.
        /// </summary>
        public static string CompleteInformacion {
            get {
                return ResourceManager.GetString("CompleteInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity type 1.
        /// </summary>
        public static string D_ObesidadTipo1 {
            get {
                return ResourceManager.GetString("D_ObesidadTipo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been saved successfully.
        /// </summary>
        public static string DataSaved {
            get {
                return ResourceManager.GetString("DataSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Data.
        /// </summary>
        public static string DataUser_Text {
            get {
                return ResourceManager.GetString("DataUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Datos {
            get {
                return ResourceManager.GetString("Datos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Detalles_Text {
            get {
                return ResourceManager.GetString("Detalles_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity type 2.
        /// </summary>
        public static string E_ObesidadTipo2 {
            get {
                return ResourceManager.GetString("E_ObesidadTipo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string Edad_Text {
            get {
                return ResourceManager.GetString("Edad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To edit  an entry  select it from the list.
        /// </summary>
        public static string EditarUserNoSelected {
            get {
                return ResourceManager.GetString("EditarUserNoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string EliminarCaptionText {
            get {
                return ResourceManager.GetString("EliminarCaptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to delete selected entry.
        /// </summary>
        public static string EliminarMessageBoxText {
            get {
                return ResourceManager.GetString("EliminarMessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To remove an entry select it from the list.
        /// </summary>
        public static string EliminarNoSelected {
            get {
                return ResourceManager.GetString("EliminarNoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing User.
        /// </summary>
        public static string ExistingUser_Text {
            get {
                return ResourceManager.GetString("ExistingUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        public static string Exit_Ques {
            get {
                return ResourceManager.GetString("Exit_Ques", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit_Text {
            get {
                return ResourceManager.GetString("Exit_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obesity type 3.
        /// </summary>
        public static string F_ObesidadTipo3 {
            get {
                return ResourceManager.GetString("F_ObesidadTipo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Fecha_Text {
            get {
                return ResourceManager.GetString("Fecha_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Genero_Text {
            get {
                return ResourceManager.GetString("Genero_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Hombre_Text {
            get {
                return ResourceManager.GetString("Hombre_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Text {
            get {
                return ResourceManager.GetString("Home_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        public static string IMC_Text {
            get {
                return ResourceManager.GetString("IMC_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light physical activity.
        /// </summary>
        public static string Indice_Actividadfisicaligera {
            get {
                return ResourceManager.GetString("Indice_Actividadfisicaligera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moderate physical activity.
        /// </summary>
        public static string Indice_ActividadfisicaMedia {
            get {
                return ResourceManager.GetString("Indice_ActividadfisicaMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extremely activity.
        /// </summary>
        public static string Indice_Personaextremadamenteactiva {
            get {
                return ResourceManager.GetString("Indice_Personaextremadamenteactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very active.
        /// </summary>
        public static string Indice_Personamuyactiva {
            get {
                return ResourceManager.GetString("Indice_Personamuyactiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sedentary.
        /// </summary>
        public static string Indice_PersonaSedentaria {
            get {
                return ResourceManager.GetString("Indice_PersonaSedentaria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Index.
        /// </summary>
        public static string IndiceActividad_Text {
            get {
                return ResourceManager.GetString("IndiceActividad_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Fat.
        /// </summary>
        public static string IndiceDeGrasa_Text {
            get {
                return ResourceManager.GetString("IndiceDeGrasa_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember that these data are approximate, and that the ideal weight varies with the complexion of the person and always consult a doctor with any questions..
        /// </summary>
        public static string InfoText {
            get {
                return ResourceManager.GetString("InfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kcal/day Recommended.
        /// </summary>
        public static string kcaldia_Text {
            get {
                return ResourceManager.GetString("kcaldia_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to load the latest data from a user.
        /// </summary>
        public static string loadData_Text {
            get {
                return ResourceManager.GetString("loadData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information provided by this program are only indicative, in no case be taken into account without consulting a medical professional..
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Mujer_Text {
            get {
                return ResourceManager.GetString("Mujer_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User.
        /// </summary>
        public static string NewUser_Text {
            get {
                return ResourceManager.GetString("NewUser_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string NoDataAviable {
            get {
                return ResourceManager.GetString("NoDataAviable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save this data for other user.
        /// </summary>
        public static string Or_Text {
            get {
                return ResourceManager.GetString("Or_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Peso_Text {
            get {
                return ResourceManager.GetString("Peso_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ideal weight.
        /// </summary>
        public static string PesoIdeal_Text {
            get {
                return ResourceManager.GetString("PesoIdeal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximun weight for your height.
        /// </summary>
        public static string PesoIdealMaximo_Text {
            get {
                return ResourceManager.GetString("PesoIdealMaximo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum weight for your height.
        /// </summary>
        public static string PesoIdealMinimo_Text {
            get {
                return ResourceManager.GetString("PesoIdealMinimo_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this app.
        /// </summary>
        public static string Rate_Text {
            get {
                return ResourceManager.GetString("Rate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Resultados_Text {
            get {
                return ResourceManager.GetString("Resultados_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save_Text {
            get {
                return ResourceManager.GetString("Save_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save to ....
        /// </summary>
        public static string SaveData_Text {
            get {
                return ResourceManager.GetString("SaveData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metabolic rate.
        /// </summary>
        public static string TasaMetabolica_Text {
            get {
                return ResourceManager.GetString("TasaMetabolica_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kcal/day recommended  for the data provided by the user.
        /// </summary>
        public static string TasaMetabolicaP1_Text {
            get {
                return ResourceManager.GetString("TasaMetabolicaP1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind Weight.
        /// </summary>
        public static string TipoPeso_Text {
            get {
                return ResourceManager.GetString("TipoPeso_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Ideal Weight.
        /// </summary>
        public static string TuPesoIdeal_Text {
            get {
                return ResourceManager.GetString("TuPesoIdeal_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users_Text {
            get {
                return ResourceManager.GetString("Users_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update User.
        /// </summary>
        public static string UsersUpdate_Text {
            get {
                return ResourceManager.GetString("UsersUpdate_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To see the graph rotate the phone.
        /// </summary>
        public static string VerGraficos {
            get {
                return ResourceManager.GetString("VerGraficos", resourceCulture);
            }
        }
    }
}
